apiVersion: v1
kind: Service
metadata:
  name: {{ include "a2a.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "a2a.labels" . | nindent 4 }}
    app: a2a
    {{- with .Values.marketplace }}
    marketplace.cloud.google.com/solution-id: {{ .solutionId | quote }}
    {{- end }}
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
    cloud.google.com/backend-config: '{"default": "a2a-backendconfig"}'
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: ClusterIP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: {{ .Values.service.protocol }}
      name: http
  selector:
    {{- include "a2a.selectorLabels" . | nindent 4 }}
    app: a2a
