apiVersion: chaos-mesh.org/v1alpha1
kind: DNSChaos
metadata:
  name: dns-random-test
  namespace: default
spec:
  action: random
  mode: all
  selector:
    namespaces:
      - default
    labelSelectors:
      'app': 'a2a-agent'
  patterns:
    - '*.craftplan.svc.cluster.local'
  duration: '30s'
---
apiVersion: chaos-mesh.org/v1alpha1
kind: DNSChaos
metadata:
  name: dns-error-test
  namespace: default
spec:
  action: error
  mode: all
  selector:
    namespaces:
      - default
    labelSelectors:
      'app': 'elrmcp-bridge'
  patterns:
    - 'postgres.default.svc.cluster.local'
    - 'redis.default.svc.cluster.local'
  duration: '30s'
