{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "craftplan.fullname" . }}-role-binding
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "craftplan.labels" . | nindent 4 }}
    app.kubernetes.io/name: craftplan
subjects:
  - kind: ServiceAccount
    name: {{ include "craftplan.serviceAccountName" . }}
    namespace: {{ .Values.global.namespace }}
roleRef:
  kind: Role
  name: {{ include "craftplan.fullname" . }}-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}