{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "a2a-erl.fullname" . }}-secret
  labels:
    {{- include "a2a-erl.labels" . | nindent 4 }}
type: Opaque
stringData:
  erlang-cookie: {{ .Values.erlang.cookie | quote }}
{{- end }}
